- CHANGELOG.md
- buildspec.yaml
I added a buildspec.yaml file to be used in the AWS Code Pipeline.
> added the buildspec.yaml file for the CI/CD pipeline

- .github/PULL_REQUEST_TEMPLATE.md
- app/styleguide/page.tsx
- app/styleguide/sg-components.tsx
This is not related to any ticket.
We needed some structure and a checklist of reminders for developers, so a PULL_REQUEST_TEMPLATE was added.
> Added PULL_REQUEST_TEMPLATE to provide structure on creating PR reviews

- CHANGELOG.md
- app/500/page.tsx
- app/login/__tests__/page.spec.tsx
- app/login/login.module.scss
- app/login/page.tsx
- app/signup/__tests__/page.spec.tsx
- app/signup/page.tsx
- app/signup/signup.module.scss
- app/styleguide/page.tsx
- package-lock.json
- package.json
- styles/_messages.scss
- styles/globals.scss
- utils/clientLogger.ts
- Added a placeholder 500 error page
- Updated signup and login pages to check for the specific errors that are now being returned by the backend controllers
- Updated associated unit tests
- Switched to using CSS Modules for signup and login pages
- address some linting issues
- added a clientlogger.ts file to be able to format client-side logs in ecs format
> Made updates to frontend auth code so that it works with the recent changes to the backend auth code

- app/styleguide/page.tsx
- package-lock.json
- Updated `dset` package version to 3.1.4
- Fixed linting issue in 'styleguide' because it was preventing me from committing my change
> Updated the dset package version to 3.1.4 in response to Dependabot vulnerability

- CHANGELOG.md
- app/template/create/select-template/__tests__/page.spec.tsx
- app/template/create/select-template/page.tsx
- components/TemplateSelectListItem/TemplateSelectListItem.module.scss
- components/TemplateSelectListItem/index.tsx
Ticket
https://github.com/CDLUC3/dmsp_frontend_prototype/issues/167
Create template builder: select template list item
Created boilerplate jest test for page, AXE test browser extension, cross browser testing.
> Template builder: Create template > select template

- CHANGELOG.md
- app/[locale]/template/[templateId]/page.tsx
- app/[locale]/template/[templateId]/section/new/__tests__/page.spec.tsx
- app/[locale]/template/[templateId]/section/new/page.tsx
- app/[locale]/template/page.tsx
- app/[locale]/template/template.module.scss
- generated/graphql.tsx
- graphql/queries/templates.query.graphql
- i18n/request.ts
- messages/en-US/global.json
- messages/en-US/templateBuilder.json
- messages/pt-BR/global.json
- messages/pt-BR/messaging.json
- messages/pt-BR/templateBuilder.json
- utils/test-utils.tsx
Updated "Add New Section" page with real data, translations, and error handling
- Added graphql query to page to get data from backend.
- Added function for sorting of data
- Added search functionality
- Added error handling
- Added unit tests
- Added translations
Fixes # ([189](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/189))
This page was tested manually tested, and tested with unit tests.
> Updated "Add New Section" page with real data, translations, and error handling

- CHANGELOG.md
- app/[locale]/styleguide/page.tsx
- app/[locale]/template/[templateId]/page.tsx
- app/[locale]/template/[templateId]/q/[q_slug]/page.tsx
- app/[locale]/template/[templateId]/q/new/__tests__/index.spec.tsx
- app/[locale]/template/[templateId]/q/new/newQuestion.module.scss
- app/[locale]/template/[templateId]/q/new/page.tsx
- app/[locale]/template/[templateId]/q/new/utils.tsx
- app/types/index.ts
- components/QuestionEdit/index.tsx
- components/QuestionEditCard/QuestionEditCard.module.scss
- components/QuestionEditCard/index.tsx
- components/QuestionTypeCard/index.tsx
- generated/graphql.tsx
- graphql/mutations/questions.mutation.graphql
- graphql/queries/questionTypes.query.graphql
- graphql/queries/questions.query.graphql
- messages/en-US/global.json
- messages/en-US/templateBuilder.json
- messages/pt-BR/global.json
- messages/pt-BR/messaging.json
- messages/pt-BR/templateBuilder.json
The page flow was changed. Instead of creating a new question when a user selects a QuestionType and redirecting them to the `template/[templateId]/q/[q_slug]/page.tsx` path with a new question id, we will wait to create the question until the user has completed the form.
This required that I move the code from `template/[templateId]/q/[q_slug]/page.tsx` into a `QuestionEdit` component, so that we can just load the `QuestionEdit` component when a user selects a questionType, without needing to redirect them.
- Hooked up the ``/template/[templateId]/q/new/page.tsx` to get data from the backend
- Moved the code from `template/[templateId]/q/[q_slug]/page.tsx` into a new `QuestionEdit` component, and updated it so that it can work with both the `q/new` page and the `q/[q_slug]` page.
- The …
> Feature/js hook up Question Type Select page

- README.md
I added some additional documentation about `cypress` functional testing in our NextJS app.
> [Chore]: Added additional documentation on cypress functional tests

- CHANGELOG.md
- buildspec.yaml
Reverting the change to buildspec for now since its not working
> Reverting the buildspec change

- package-lock.json
- package.json
As part of my earlier changes to use Dockerfile.prod, I installed 'sharp' which was missing
> Dockerfile.prod changes - installed 'sharp' which is required in standalone mode

- CHANGELOG.md
- app/[locale]/projects/[projectId]/__tests__/page.spec.tsx
- app/[locale]/projects/[projectId]/page.tsx
- app/[locale]/projects/[projectId]/project/page.tsx
- generated/graphql.tsx
- graphql/queries/projects.query.graphql
- messages/en-US/planBuilderProjectOverview.json
- Updated Project Overview page with data from backend (path: `projects/[projectId]`
- Added new `Plans` info from backend
Fixes # ([339](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/339))
Manually and via unit test
> Updated Project Overview page

- CHANGELOG.md
- Dockerfile.prod
- app/[locale]/template/[templateId]/q/[q_slug]/page.tsx
- components/QuestionAdd/index.tsx
- components/QuestionPreview/index.tsx
- components/QuestionView/__tests__/index.spec.tsx
- components/QuestionView/index.tsx
I merged [this node version update](https://github.com/CDLUC3/dmsp_frontend_prototype/pull/407), but the Codepipeline failed because i forgot to update the node images everywhere in the `Dockerfile.prod` file.
I then found a bunch of typescript errors when trying to commit the change, so i fixed those.
> Fixed wrong node image in Dockerfile.prd and fixed a number of linting issues

- CHANGELOG.md
- app/[locale]/template/[templateId]/section/new/__mocks__/mockPublishedSections.json
- app/[locale]/template/[templateId]/section/new/__tests__/page.spec.tsx
- app/[locale]/template/[templateId]/section/new/newSectionPage.module.scss
- app/[locale]/template/[templateId]/section/new/page.tsx
- messages/en-US/templateBuilder.json
- messages/pt-BR/templateBuilder.json
Finishes #486
related to [backend PR](https://github.com/CDLUC3/dmsp_backend_prototype/pull/276) 
**Add new Section page**
- added new `bestPractice` and `filteredBestPractice` states so we can separate them from the affiliation's sections
- added a Load More button to both sections
- added a `visibilityCount` state to help the Load more section show the correct number of sections
- added `handleLoadMore` and `renderLoadMore` functions
- added SCSS module for the new "Load more" button
- updated the function handling the results of fetching the data to separate out the bestPractice sections
- added new translations to support the load more button
- All existing tests pass
- Verified manually via the UI
> Fix bugs with adding a new Section by copying another

- CHANGELOG.md
- app/[locale]/account/profile/__tests__/page.spec.tsx
- app/[locale]/account/profile/page.tsx
- messages/en-US/global.json
- messages/pt-BR/global.json
- Added missing translation keys to the User Profile page.
- 
Fixes # ([526](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/526))
Manual and unit tests
> Fixed missing translations on User Profile page

- CHANGELOG.md
- app/[locale]/account/profile/page.tsx
- app/[locale]/account/profile/profile.module.scss
- components/UpdateEmailAddress/__tests__/index.spec.tsx
- components/UpdateEmailAddress/index.tsx
- components/UpdateEmailAddress/updateEmailAddress.module.scss
- messages/en-US/global.json
- messages/pt-BR/global.json
- styles/_elements.scss
- styles/_typography.scss
- utils/routes.ts
Fixed the issues for the demo mostly styling issues and a bit of clean up in #515 and #509
Fixes # (issue)
- "Receives notifications" has characters in text #515
- Related Actions list starting just a bight higher than the profile box: #509
- Headers in Email box being more indented than their sub points #509
- Not much spacing at the bottom compared to lots of white space at the top. I'm okay with either (I think I prefer it a bit more condensed) but looks odd to be so different across the page: #509
- Using routePath function rather than hard coded URLS
Unit testing is in place for the changes, the visual changes were tested in the browser and on various devices
> Bug/profile page fix related action spacing #509 and #515

- CHANGELOG.md
- app/[locale]/email/confirm-email/[userId]/[token]/page.tsx
I just merged my PR with dependency updates, https://github.com/CDLUC3/dmsp_frontend_prototype/pull/550, but there was a new type error that emerged that was breaking the build.
I addressed the bug that is in the ConfirmEmailPage component. This component is not currently being used, and will need to be updated when we implement the email notifications in the backend.
Ran unit tests and linting tests
> Fixed bug related to a type error that was breaking build

- CHANGELOG.md
- app/[locale]/styleguide/page.tsx
- components/Form/DateComponent/datePicker.module.scss
- components/Form/DateComponent/index.tsx
- components/Icons/__tests__/index.spec.tsx
- components/Icons/index.tsx
- public/icons/iconset.svg
- styles/form/_button.scss
- Added a different color for the Date Picker heading to increase contrast and make it more accessible
- Added some additiona Google material arrow icons to be used by the Date Picker
Fixes # ([597](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/597))
Manual testing and with unit test
> [Bug fix] - Added a different color for the Date Picker heading to increase contrast and make it more accessible

- CHANGELOG.md
- app/[locale]/projects/[projectId]/dmp/[dmpid]/related-works/__tests__/page.spec.tsx
- app/[locale]/projects/[projectId]/dmp/[dmpid]/related-works/page.tsx
- app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/CommentsDrawer.tsx
- app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/PlanOverviewQuestionPage.module.scss
- app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/page.tsx
- app/[locale]/styleguide/page.tsx
- components/RelatedWorksList/__tests__/index.spec.tsx
- components/RelatedWorksListItem/RelatedWorksListItem.module.scss
- components/RelatedWorksListItem/__tests__/index.spec.tsx
- components/RelatedWorksListItem/index.tsx
- messages/en-US/relatedWorks.json
- styles/_elements.scss
- styles/form/_button.scss
- styles/globals.scss
Made the following changes to the Related Works UI:
- Changed language of buttons to "Accept" and "Reject".
- Changed language of tabs to "Accepted" and "Rejected".
- Changed "Review" on "Pending" tab to say "Expand".
- Moved accept/reject buttons to the bottom right corner of cards, so that they can be accepted or rejected before being expanded.
- Changed the order of accept/reject buttons so that accept comes first.
Also added a small button CSS class `button.small` and added it to the style sheet. I noticed that all buttons have a 10px margin on the right and thought that this makes it harder to re-use them, because you can't control the spacing from the parent container (e.g. with flex gap) without overriding the margin, so I also removed this and have tried to find places where the …
> Related works UI improvements

- .editorconfig
- CHANGELOG.md
- app/[locale]/projects/[projectId]/dmp/create/__tests__/page.spec.tsx
- app/[locale]/projects/[projectId]/dmp/create/page.tsx
- generated/graphql.tsx
- graphql/mutations/plans.mutations.graphql
- utils/errorHandler.ts
When creating a new DMP. We automatically add all the funders that already exist on the project to the DMP.
Fixes #683
While working on this I also tidied up the related test suite.
- Manual testing by running the development server and creating a new DMP, then selecting a template.
- Added new unit tests, and ran the test-suite to make sure tests are passing
- Ran the `type-check`, `lint` and `build` commands to ensure that there are no
type issues.
> Ae 683 preselect plan funder

- CHANGELOG.md
- app/[locale]/account/update-password/__tests__/page.spec.tsx
- app/[locale]/account/update-password/page.tsx
- app/[locale]/account/update-password/updatePassword.module.scss
- messages/en-US/global.json
- messages/pt-BR/global.json
Profile Update your password page 
https://github.com/CDLUC3/dmsp_frontend_prototype/issues/830
Added unit testing
> Static: Update password page

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- eslint.config.js
- package-lock.json
For this branch, I merged main into this stage branch first, and then resolved merge conflicts before submitting this PR.
> Merge stage to main

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- eslint.config.js
- package-lock.json
Pulling the latest from main and stage into development to fix merge conflict with `package-lock.json`
> Merge stage/main into development
