buildspec.yaml

- Change to image tag from `latest` to `nextJS-latest` to help identify them as compared to `apollo-latest`
- Switched ENV variable defined by CodeBuild from `BUILD_ENV` to `NODE_ENV` as this seems more useful for our JS node based apps
- Added `TASK_DEFINITION_CONTAINER_NAME` env variable in CodeBuild so that the artifact generated by the code build will be able to be deployed to the correct ECS service
- Added `artifact` designation using the standard `imagedefinitions.json` that CodeDeploy is looking for

Changes to the buildspec to support deployment to ECS

---

app/healthcheck/page.tsx

The AWS load balancer requires a health check. The current homepage returns a 500 at the moment, so the ALB will not direct traffic to nextJS.
I have added a simple health check page here. I tried to override the default layout, so that it just returns something very simple like `<html><body>Ok</body></html>` but couldn't figure out how to do that.
Once this is merged to development, it should auto-deploy to ECS and the site should become available

added healthcheck page for the application load balancer

---

CHANGELOG.md
app/login/__tests__/page.spec.tsx
app/login/page.tsx
app/signup/__tests__/page.spec.tsx
app/signup/page.tsx

We need to add some controls on the frontend to stop users from repeated submit attacks. I implemented a loading state to disable the "submit" button while the POST request is being made. That way a user is prevented from repeatedly pushing the button to start new requests while the request is in progress.
I also added an "attempts" state. After 5 attempts, the user gets an error message telling them that there were too many attempts, and that they need to wait before tying again.
The messaging, and possibly some of the functionality, will be updated when the designs for these pages come in. However, I just wanted to put some minimal defenses in place to remind us to address these with the finalized pages.
Fixes # ([#66](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/66)
Please …

Added logging state and velocity controls to the login and signup forms

---

CHANGELOG.md
__tests__/middleware.spec.ts
middleware.ts

After we added the `[locale]` directory, the `/login` page was giving a **404** error in the middleware.
We need to update the logic in the middleware to add `login` and `signup` page to the exclusion list, and remove the return response for all excluded pages.
Fixes # ([194](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/194))
Run unit tests and manually tested
- [NA] I have added tests that prove my fix is effective or that my feature works

Fixed /login 404 issue related to new [locale] directory

---

CHANGELOG.md
app/[locale]/template/[templateId]/q/[q_slug]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/q/[q_slug]/page.tsx
app/[locale]/template/[templateId]/q/[q_slug]/questionEdit.module.scss
app/[locale]/template/[templateId]/q/new/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/q/new/page.tsx
app/[locale]/template/[templateId]/q/new/utils.tsx
app/types/index.ts
components/Form/FormInput/index.tsx
components/Form/FormTextArea/__tests__/index.spec.tsx
components/Form/FormTextArea/index.tsx
components/Form/QuestionOptionsComponent/__tests__/index.spec.tsx
components/Form/QuestionOptionsComponent/index.tsx
components/Form/QuestionOptionsComponent/optionsComponent.module.scss
components/QuestionAdd/__tests__/index.spec.tsx
components/QuestionAdd/index.tsx
components/QuestionAdd/questionAdd.module.scss
components/QuestionEdit/index.tsx
components/QuestionEdit/questionEdit.module.scss
components/QuestionTypeCard/index.tsx
generated/graphql.tsx
graphql/mutations/questions.mutation.graphql
graphql/queries/questions.query.graphql
jest.config.ts
messages/en-US/global.json
messages/en-US/templateBuilder.json
messages/pt-BR/global.json
messages/pt-BR/messaging.json
messages/pt-BR/templateBuilder.json
styles/_forms.scss

- Updated the Edit Question `template/[templateId]/q/[q_slug]/page.tsx` with actual data from backend and added functionality for `options` and text question types
- Updated the Add Question`template/[templateId]/q/new/page.tsx` page with actual data from backend and added functionality to accomodate `option` and text question types.
- Added new Question and QuestionOption types
- Added useSampleTextAsDefault checkbox to both the Edit and Add Question pages, which should only display when the user selects the `Text Area` or `Text Field` question types
- Updated the shared FormInput component, and added a new FormTextArea component
- Added new QuestionOptionsComponent for handling the `options` question types in the form
- Added new QuestionAdd component for adding a new question
- Added …

Hook up the Edit and Add Question pages and add fields and functionality for current question types

---

CHANGELOG.md
docker-compose.yml

I recently made some changes to `docker-compose.yml` file, and forgot to revert a change to it where I set the environment to `production`.
This caused the `EvalError`. It is working now.
Ran existing unit tests and checked that I could access pages

[Bug] - Fix 'EvalError: Code generation from strings' error when trying to access pages in app

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/download/page.tsx

Fixed bug that was breaking the build.  The fix was in `/projects/[projectId]/dmp/[dmpId]/download` because of the unused `FileIcon` variable.
Fixes # ([376](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/376))
Tested that build now passes

removed unused var from /projects/[projectId]/dmp/[dmpId]/download which broke the build

---

CHANGELOG.md
Dockerfile.prod

Pipeline build failed again. This time I made sure to test that I could build `docker build -f Dockerfile.prod -t test-image .`, and it worked when I added back the missing `as deps`.

Fixed missing 'as deps' in Dockerfile.prod

---

CHANGELOG.md
app/[locale]/template/[templateId]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/access/page.tsx
app/[locale]/template/[templateId]/page.tsx
app/[locale]/template/[templateId]/q/[q_slug]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/q/[q_slug]/page.tsx
app/[locale]/template/[templateId]/section/[section_slug]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/section/[section_slug]/page.tsx
app/[locale]/template/[templateId]/section/create/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/section/create/page.tsx
app/[locale]/template/__tests__/page.spec.tsx
app/[locale]/template/page.tsx
components/Modal/ConfirmModal.tsx
components/QuestionAdd/__tests__/index.spec.tsx
components/QuestionAdd/index.tsx
components/QuestionPreview/index.tsx
components/QuestionView/index.tsx
components/SelectExistingTemplate/index.tsx
messages/en-US/global.json
messages/en-US/questionView.json
messages/en-US/templateBuilder.json
messages/pt-BR/global.json
messages/pt-BR/questionView.json
messages/pt-BR/templateBuilder.json

- Fixed bugs related to the template builder flow
- Fixed Preview page to not display HTML at top for Requirements [#449]
- Added redirect back to Edit Template page when user creates a new Section [#452]
- On `/template` page, fixed the `published` and `unpublished` labels on the list items because they were reversed [#453]
- Replaced hard-coded org names with the actual org names in text on `Manage access` page, and fixed archive modal title to `Confirm removal` [#454]
- Changed `Published` to `Last updated` on `/template/[templateId]` page and fixed missing translation for `Load 3 more`. Also when adding a new `Question`, the button should say `Save and add` and when editing an existing question, the form button should say `Save and update`. [#455]
- Added missing space after `Guidance …

Fixed bugs related to the template builder flow

---

app/[locale]/template/[templateId]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/actions/index.tsx
app/[locale]/template/[templateId]/actions/updateTemplateAction.ts
app/[locale]/template/[templateId]/page.tsx
components/PageHeader/index.tsx
components/PageHeaderWithTitleChange/__tests__/index.spec.tsx
components/PageHeaderWithTitleChange/index.tsx
components/PageHeaderWithTitleChange/pageheaderWithTitle.scss
generated/graphql.tsx
graphql/mutations/templates.mutation.graphql
graphql/queries/templates.query.graphql
messages/en-US/templateBuilder.json
messages/pt-BR/templateBuilder.json
styles/globals.scss
utils/graphqlServerActionHandler.ts

Per this wireframe, https://www.figma.com/proto/RRtoRLyr5Spf0KiyRfEclt/DMP-Tool-Wireframes?node-id=6-333&t=N2jvNbe3g9eOxDc7-0&scaling=scale-down-width&page-id=6%3A66&starting-point-node-id=69%3A345&content-scaling=fixed&show-proto-sidebar=1, we need to provide a link that allows users to edit a template title on the Template Overview page (i.e., `/template/[templateid]`).
- Created another version of our shared `PageHeader`, called `PageheaderWithTitleChange` to be used with pages that need to have this `edit title` functionality alongside the `page title`. Since we needed to add a good amount of new code for this new functionality, it made sense to create this second `page header` component so that the rest of the pages aren't weighed down with code that they don't use.
Fixes # …

Add change title functionality on Template Overview page

---

CHANGELOG.md
app/[locale]/template/[templateId]/q/[q_slug]/page.tsx
components/PageHeaderWithTitleChange/pageheaderWithTitle.scss
components/QuestionAdd/index.tsx

Converted Sample Text field to Rich Text Editor type on Question Forms
Fixes # ([455](https://github.com/CDLUC3/dmsp_frontend_prototype/pull/455))
Tested manually

Converted sample text field to Rich Text Editor in Question forms

---

.env.example
CHANGELOG.md
app/[locale]/template/[templateId]/page.tsx
utils/server/graphqlServerActionHandler.ts

Currently, when a user publishes a template on the Template Overview page (`template/[templateId]`), the template does not refresh.
Added a call to `refetch()` the data.
Also, added a new env variable, `SERVER_ENDPOINT` to be used in server-side components for `/graphql` endpoints since the env variables prefixed with `NEXT_PUBLIC` are only for client-side components.
Fixes # ([455](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/455))
Tested manually

Fixed issue with template not refreshing after user clicks 'publish'

---

CHANGELOG.md
app/[locale]/template/[templateId]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/page.tsx
messages/en-US/templateBuilder.json

- Fixed typo and ensure that correct visibility text displays when changing the
Private/Public status in the Template Publish Modal [#483]
Fixes #483 
- Manual testing by navigating to the Template create page, Creating a template, and then clicking the publish modal. I then verified that the text updates when I change visibility a number of times.
- Also created a new unit test to verify that the text is updated correctly
- I ran `npm run lint` and `npm run type-check` against my new code to ensure that there are no typing and linting issues.

Ae 483 publish modal typo

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/feedback/invite/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/fundings/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/fundings/page.tsx
app/[locale]/projects/create-project/__tests__/page.spec.tsx
app/types/index.ts
components/Form/QuestionComponents/RadioButtonsQuestionComponent/__tests__/index.spec.tsx
components/Form/RadioGroup/index.tsx
components/QuestionView/__tests__/index.spec.tsx
generated/graphql.tsx
graphql/mutations/plans.mutations.graphql
graphql/queries/fundings.query.graphql
messages/en-US/global.json

Hooked up the Plan funders page so that the user can select the funder for their
plan.
Fixes #363
- Tested by running the `npm run build` command manually, and checking for errors related to my code
- Also ran `npm run type-check` to make sure I didn't introduce any type errors
- I tested by manually checking that I can pick a funder for a dmp by creating a new Plan in an existing project, clicking on the link for funding, and then selecting the funder from there.
- Created automated unit tests; Checked that they pass, didn't introduce new errors, and also that the coverage is 100%

AE - Plan Funder data integration

---

CHANGELOG.md
app/[locale]/projects/[projectId]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/page.tsx

This bug was filed because `to` was displaying when project start and end dates were not available on the `Project Overview` page.
We decided that if `startDate` or `endDate` are missing, we will not display that line.
-Prevent the project date from displaying if either `startDate` or `endDate` are not available.
Fixes # ([588](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/588))
Tested manually and using unit test.

[Bug fix] - Prevent the project date section from displaying if startDate or endDate are missing

---

CHANGELOG.md
app/[locale]/projects/[projectId]/members/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/members/page.tsx
utils/routes.ts

- Updated `projects/[projectId]/members` page to have consistent breadcrumbs as the `Project overview` page
- Updated `routePath` with route `projects.share.index` and updated unit test for `ProjectsProjectMembers`
Fixes # ([589](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/589))
Tested manually and with unit test
1. Go to a project that has project members (e.g., http://localhost:3000/en-US/projects/1)
2. Click on `Edit project members` link to go to the `Project members` page
3. On the `Project members` page, you should see the …

Fixed ProjectsProjectMembers breadcrumb

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/page.tsx

- Updated `Plan Overview` page so that we use the text `Start` on the section button if a user has not answered any questions yet in that section. If they have, then we continue to use the text `Update` on the button.
Fixes # ([594](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/594))
Manually test and added unit test.

Updated the plan overview page to use the text 'Start' on the section button

---

CHANGELOG.md
app/[locale]/projects/[projectId]/funding-search/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/funding-search/page.tsx
generated/graphql.tsx
graphql/queries/fundings.query.graphql
messages/en-US/global.json

Added the most popular funders to the funding search page _when creating a new project_.
Fixes #380
- Created new automated test and related mocks to check that the correct graphQL queries are called.
- Automated tests also check that selecting a popular funder will add the funder to the project just like searching for a funder would.
- Did manual testing where I clicked through to this page, verified that the popular funders are show, and that I can click to pick one of the popular funders.

Add popular funders to the funder search page when creating a new project

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/page.tsx
app/[locale]/template/[templateId]/q/[q_slug]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/q/[q_slug]/page.tsx
components/Form/QuestionComponents/MultiSelectQuestionComponent/index.tsx
components/QuestionAdd/__tests__/index.spec.tsx
components/QuestionAdd/index.tsx
components/TinyMCEEditor/tinyMCEEditor.module.scss
messages/en-US/global.json
messages/pt-BR/global.json
utils/routes.ts

- Updated both the `QuestionAdd` and `QuestionEdit` components to include radio buttons to set the question as `required`
- Made some small changes to `QuestionAdd` to use `routePath` in places that weren't using it
- Updated `utils/routes` to include `usage description`
- Fixed a small bug in `Multistate` component.
- Updated associated unit tests
- Removed a margin from below the TinyMCEEditor, because it was causing the `help text` to be far below the editor in the QuestionAdd and QuestionEdit pages
- Added translation keys
Fixes # ([562](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/562))
Manual and unit tests.
Please make sure to do a careful merge of development branch into yours, to make …

Added radio buttons to QuestionAdd and QuestionEdit to allow users to set question as required

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/actions/index.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/actions/updatePlanTitleAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/page.tsx
app/[locale]/template/[templateId]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/page.tsx
components/PageHeaderWithTitleChange/__tests__/index.spec.tsx
components/PageHeaderWithTitleChange/index.tsx
components/PageHeaderWithTitleChange/pageheaderWithTitle.scss
generated/graphql.tsx
graphql/mutations/plans.mutations.graphql
messages/en-US/global.json
messages/en-US/planBuilderPlanOverview.json
messages/en-US/templateBuilder.json
messages/pt-BR/global.json
messages/pt-BR/planBuilderPlanOverview.json
messages/pt-BR/planBuilderProjectOverview.json
messages/pt-BR/templateBuilder.json
utils/errorHandler.ts

- Updated the `Plan Overview` page to use the `PageHeaderWithTitleChange` component to allow users to edit the `Plan title`
- Made updates to the `PageHeaderWithTitleChange` to allow link text and label text to be passed in as props. 
- Added a `updatePlanTitleAction` to be used for to call the `updatePlan` mutation
- Made updates to the `Template Edit` page in order to pass in the new `linkText` and `label` props to `PageHeaderWithTitleChange`
- Added a shared `extractErrors` function to extract the field-level errors returned from the backend
- Added translation keys
- Updated associated unit tests
Fixes # ([608](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/608))
Manually and via unit tests
- [*] Any dependent changes have been merged and published in downstream modules …

Added the ability to edit the plan title

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/page.tsx
app/[locale]/template/[templateId]/__tests__/page.spec.tsx
app/[locale]/template/[templateId]/page.tsx
components/PageHeaderWithTitleChange/__tests__/index.spec.tsx
components/PageHeaderWithTitleChange/index.tsx
generated/graphql.tsx
graphql/mutations/templates.mutation.graphql
messages/en-US/templateBuilder.json
messages/pt-BR/templateBuilder.json

We recently updated `Plan Overview` and `Template Edit` pages to allow users to change the plan and template titles. However, after saving the new title, we were calling `refetch` to reload the data, but the experience was jerky. So `optimistic updates` were applied in both cases
Fixes # ([625](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/625))
This was tested manually and using unit tests
https://github.com/user-attachments/assets/10258019-51da-4fe4-82b2-d1b570035592
https://github.com/user-attachments/assets/ddfd8827-2061-45f5-a2 …

[Bug fix] - Made updates to use optimistic updates for Plan and Template title changes

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/PlanOverviewPage.module.scss
app/[locale]/projects/[projectId]/dmp/[dmpid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/page.tsx
utils/general.ts

s and the Plan Status displayed was in all caps
On the Plan Overview page, the links in the side panel were different sizes. The cause was because a couple of the `<Link/>` tags didn't include an `href` since it cause some flashing when switching to a Select dropdown, say. I updated the `Update` link to use a `<Button>` component instead.
- I smoothed out the Plan Status update
- I updated unit tests
Fixes # ([634](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/634))
Manual testing and unit tests
Please make sure to do a careful merge of development branch into yours, to make sure you aren't reverting or effecting any previous commits to the development …

[Bug] - Fixed bug where links in Plan Overview sidebar were of different sizes

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/PlanOverviewQuestionPage.module.scss
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/page.tsx
app/[locale]/projects/[projectId]/funding-search/page.tsx
components/ExpandableContentSection/index.tsx
components/QuestionView/QuestionView.module.scss
components/QuestionView/index.tsx
messages/en-US/global.json
messages/pt-BR/global.json

Even though the Best Practices are just hard-coded right now, I wanted to add the new expanding/collapsing Best Practices that was added to the `Question Preview` to the `Question Details` page for consistency.
Fixes # ([638](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/638))
Tested manually and with unit tests

Added the new expanding/collapsing Best Practices to Question Detail page

---

CHANGELOG.md
app/[locale]/projects/[projectId]/fundings/page.tsx
app/[locale]/projects/[projectId]/fundings/search/page.tsx
app/[locale]/projects/[projectId]/page.tsx
components/Form/TypeAheadWithOther/typeaheadWithOther.module.scss

- Updated `Project Funding` page to use correct `projectFundingId` when clicking `edit` and changed the `fetchPolicy` to make sure it always grabs latest list of `funding` when the user arrives at the page
- Added `commas` in between `funder` names on the `Project Overview` page
- Updated the `Project Funding Search` page to use same `max-widths` for the funder lists
Fixes # ([643](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/643), [650](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/650))
Tested manually and checked unit tests …

Fixed bugs in the Project Funding and Project Overview pages

---

CHANGELOG.md
app/[locale]/projects/[projectId]/funding-search/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/funding-search/page.tsx
app/[locale]/projects/[projectId]/fundings/add/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/fundings/add/addFunderManually.module.scss
app/[locale]/projects/[projectId]/fundings/add/page.tsx
app/[locale]/projects/[projectId]/fundings/search/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/fundings/search/page.tsx
generated/graphql.tsx
graphql/mutations/affiliations.mutation.graphql
messages/en-US/planBuilderProjectOverview.json
utils/routes.ts

- Added the missing page for adding a funder manually.
- Added new routes for this page.
- Added new graphql mutations related to this page.
Fixes #497
- Added unit tests to test that we get the expected behaviour.
- Manual testing by running through the create-project workflow, and choosing "Add Funder Manually" button during the search for funder step. Entered the details and checked that the funder is created and we are redirected to the project funding page.

Ae 497 add funder manually

---

CHANGELOG.md
messages/en-US/global.json

- Updated the translation used for `typeaheadSearch` to `Affiliation search`
Fixes # ([645](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/645))
Manual test

[Bug fix] - Fixed inconsistent naming for question type Affiliation Search

---

CHANGELOG.md
app/[locale]/__tests__/layout.spec.tsx
styles/_page.scss

Fixed issue with the `Back` button link turning white when a user hovers over it. This is because a base style of buttons sets the color white. I just made sure that for the `Back` button link, that it keeps the default gray color.
I created another ticket, #657 , to think about what we expect the `Back` button to do, and how often we want to use it, since we also have `breadcrumb` links.
Fixes # ([651](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/651))
Manually tested

[Bug fix] - Fixed issue with text turning white when hovering over Back button

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/create/PlanCreate.md
app/[locale]/projects/[projectId]/dmp/create/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/create/page.tsx
app/[locale]/projects/[projectId]/fundings/page.tsx
app/types/index.ts
components/Form/CheckboxGroup/index.tsx
components/Pagination/__tests__/index.spec.tsx
components/Pagination/index.tsx
components/Pagination/pagination.module.scss
components/TemplateList/index.tsx
generated/graphql.tsx
graphql/queries/templateVersions.query.graphql
messages/en-US/global.json
messages/en-US/planBuilderProjectOverview.json
messages/pt-BR/global.json
messages/pt-BR/planBuilderPlanOverview.json
messages/pt-BR/planBuilderProjectOverview.json
styles/globals.scss

This ticket was filed because the page never loaded more than the default 20 results that the backend started to return when it updated to use pagination queries.
- I updated the `Plan Create` page to use the new `pagination queries`, moving off of the manual `Load more` functionality we had in place
- Added use of `routePath` on page
- Added a new, accessible `Pagination` component, which is used in the updated `Plan Create` page. When adding the pagination, I tried to comply with the WCAG 2.5.5 `AA` tap size requirements of `24px x 24px`
- Updated unit test for `Plan Create` to use the `MockedProvider` and added some new unit tests
- Added translation keys
Fixes # ([686](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/686))
This was …

Updated Plan Create page to use new pagination queries and added Pagination component

---

CHANGELOG.md
__mocks__/common/mockPublishedQuestionDataForTextArea.json
app/[locale]/projects/[projectId]/dmp/[dmpid]/fundings/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/page.tsx
jest.config.ts
messages/en-US/global.json
messages/pt-BR/global.json
utils/general.ts

Although we previously added a function, `stripHtmlTags` to strip tags out of question and section text that was being added, we didn't implement that for question text that had been seeded. Since we will be migrating data from the current tool to the new rebuild, we will need to strip out HTML tags from the question text as well.
- Implemented `stripHtmlTags` on `question text` on the `Question Details` page
- Updated `stripHtmlTags` function to include an option to only remove specified tags
- Added `.js` extension to `next/jest.js` import in `jest.config.ts`, because it was causing errors related to ESM strict requirements when using node v22.18.0
Fixes # ([662](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/662))
Manually tested …

[Bug fix] - Stripped HTML tags from question text

---

CHANGELOG.md
messages/en-US/templateBuilder.json
messages/pt-BR/templateBuilder.json

Small PR to fix the erroneous use of `question` text in the help text on the `Section` pages.
- Updated translation values.
Fixes # ([666](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/666))
Manual testing

[Bug fix] - Changed 'question' text to the correct `section` text

---

CHANGELOG.md
app/[locale]/projects/[projectId]/fundings/[projectFundingId]/edit/page.tsx

When on the `Funding Detail` page for a funding source, data appeared to not be updated when a user made changes and saved. However, when we refreshed the page, we saw the new data. The problem was that we were seeing stale, cached data.
- Added `fetchPolicy: 'network-only'` to the funding query, so that it always loads fresh data.
I believe this is ok because edit pages are low traffic pages, and we need to make sure that users always see the latest data so that they don't overwrite existing data.
Fixes # ([659](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/659))
Manually tested
Please make sure to do a careful merge of development branch into yours, to make sure you aren't reverting or effecting any previous commits to the …

[Bug fix] Fixed issue with saved data not loading on the Funding Detail 

---

CHANGELOG.md
app/[locale]/template/[templateId]/section/new/page.tsx

I wanted to double check that the sections were displaying as expected, because when I was testing on `dev`, I didn't see any sections.
It is working, but I did make a change to hide the `<h2>` heading for each of the section lists (Org and Best practice) if there is nothing to display.
Fixes # ([702](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/702))
Manually tested
Showing an example of the "Org" sections and "Best Practice" sections displaying correctly on the page.
https://github.com/user-attachments/assets/d40d70d2-bd7c-4d2e-8 …

Small change to hide section headings if there is nothing to display

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/page.tsx
components/hooks/useRenderQuestionField.tsx
generated/graphql.tsx
graphql/queries/questions.query.graphql

Currently, even if a `textArea` `question` is created with `sampleText` and with `useSampleTextAsDefault` is true, we are not using it on the Question Detail page.
- Updated the `content` value for `textAreaProps` to initially use the `sampleText` value if there is `sampleText` and `useSampleTextAsDefault` is true.
- Added a unit test for it
Fixes # ([677](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/677))
Manually tested and tested with unit test

[Bug fix] - Updated Question Detail page to use sampleText if useSampleTextAsDefault is true

---

CHANGELOG.md
components/QuestionAdd/__tests__/index.spec.tsx
components/QuestionAdd/index.tsx

- Added back some code for affiliation event handlers and updated location of `label` and `help` text in `json` so that the updated values appear on the`Question Preview` page. (See screenshots for further description)
Fixes # ([669](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/669))
Manually tested and updated unit tests.

[Bug fix] - Fixed issue with entered Affiliation Label and Help text not displaying on Question Preview page

---

CHANGELOG.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/__tests__/CommentList.spec.tsx
app/[locale]/template/[templateId]/history/__tests__/page.spec.tsx

- Updated unit tests for `/template/[templateId]/history/__tests__/page.spec.tsx` and `/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/__tests__/CommentList.spec.tsx` which broke because dates tested were assumed to always be from same timezone. 
Fixes # ([739](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/739))
Tested my changes by running tests in the `Pacific/Auckland` timezone: `TZ=Pacific/Auckland npm test`

[Bug fix] - Fixed issue with some breaking unit tests due to different timezones

---

.env.example
CHANGELOG.md
README.md
app/[locale]/projects/[projectId]/dmp/[dmpid]/__tests__/page.spec.tsx
app/[locale]/projects/[projectId]/dmp/[dmpid]/page.tsx
app/[locale]/styleguide/page.tsx
lib/constants.ts
styles/form/_button.scss

- Replaced the previous Preview button on the Plan Overview page with a <Link> that goes to the `dmptool-narrative-generator` endpoint to load a new HTML page in another tab
Fixes # ([412](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/412))
Manually and with unit test
https://github.com/user-attachments/assets/af8adbe4-ee1d-4878-ac45-67788a22e505

Add preview functionality for plan

---

.env.example
CHANGELOG.md
README.md
app/[locale]/projects/[projectId]/collaboration/actions/removeProjectCollaboratorAction.ts
app/[locale]/projects/[projectId]/collaboration/actions/resendInviteToProjectCollaborator.ts
app/[locale]/projects/[projectId]/collaboration/actions/updateProjectCollaboratorAction.ts
app/[locale]/projects/[projectId]/collaboration/invite/actions/addCollaboratorAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/actions/publishPlanAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/actions/updatePlanStatusAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/actions/updatePlanTitleAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/members/actions/addPlanMemberAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/actions/addAnswerAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/actions/addAnswerCommentAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/actions/addFeedbackCommentAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/actions/removeAnswerCommentAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/actions/removeFeedbackCommentAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/actions/updateAnswerAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/actions/updateAnswerCommentAction.ts
app/[locale]/projects/[projectId]/dmp/[dmpid]/s/[sid]/q/[qid]/actions/updateFeedbackCommentAction.ts
app/[locale]/projects/[projectId]/fundings/[projectFundingId]/edit/actions/removeProjectFundingAction.ts
app/[locale]/template/[templateId]/actions/updateSectionDisplayOrderAction.ts
app/[locale]/template/[templateId]/actions/updateTemplateAction.ts
app/api/check-auth/__tests__/route.spec.ts
app/api/check-auth/route.ts
utils/server/__tests__/logger.spec.ts
utils/server/__tests__/loggerUtils.spec.ts
utils/server/graphqlServerActionHandler.ts
utils/server/logger.ts
utils/server/loggerUtils.ts
utils/server/serverAuthHelper.ts

Part of [#14](https://github.com/CDLUC3/dmptool-infrastructure/issues/14)
- Added a new `SERVER_LOG_LEVEL` env variable 
- Update `utils/server/logger.ts` to add Pino redaction logic and also a `createLogger` function that allows an optional destination to be passed in to facilitate testing. The default is the normal stdout.
- Updated `utils/server/serverAuthHelper` by adding a `serverFetchAccessToken` to fetch the access token so we can include things like the `jti` in logs
- Added `utils/server/loggerUtils.ts` with a function that will prepare objects for logging. It strips out properties with null/undefined values, and redacts any instances of keys that we don't want in the logs
- Added logging to the `graphqlServerActionHandler.ts` 
- Added some missing `try -> catch` blocks to …

Updates to logging to support OpenSearch

---

CHANGELOG.md
app/[locale]/signup/__tests__/page.spec.tsx
app/[locale]/signup/page.tsx
app/[locale]/signup/signup.module.scss
app/[locale]/template/__mocks__/templateListPage.mocks.ts
messages/en-US/global.json
messages/pt-BR/global.json
styles/form/_button.scss

- Updated the `/signup` page to gray out/disable the `email` field on step 2, so that the email value doesn't inadvertently change when the user starts adding their first and last name.
- Added a `Back` button on step 2, so that a user has the ability to go back and change their email address
- Added unit tests
- Fixed console warning regarding missing mock in a unit test for `/template`
Fixes # ([769](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/769))
Manually tested and tested with new unit tests
- Note that the email field is …

Update signup to gray out email field

---

CHANGELOG.md
middleware.ts

In some scenarios, when the middleware refreshes the auth token, the user gets a 404 error. This is because the middleware executes before the actual route is resolved. We set the cookies and return NextResponse.next(), but the request continues without retrying the navigation with the new cookies. To fix this, I updated the middleware to redirect back to the same url to get the new tokens from the browser cookies.
Fixes # ([848](https://github.com/CDLUC3/dmsp_frontend_prototype/issues/848))
Manually tested with existing unit tests still passing
Please make sure to do a careful merge of development branch into yours, to make sure you aren't reverting or effecting any previous commits to the development …

Fixed middleware to redirect back to same url after token refresh
